name: Jest Tests
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: |
        npm install jest-junit --save-dev
        npx jest --reporters=default --reporters=jest-junit

    - name: Upload Jest test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: jest-test-results
        path: ./junit.xml
        retention-days: 30